version: '3'
services:
  nodejs_server:
    image: "node:10.14.0"
    container_name: "task_server"
    volumes:
      - ./task_server/:/app
    working_dir: /app
    depends_on:
      - mongo
    ports:
      - 3000:3000
    networks:
      - task_network
    command: 'npm start'
    environment:
      NODE_ENV: production
    restart: always
  mongo:
    image: mongo:latest
    container_name: "task_mongo"
    volumes:
      - ./mongo_db/data:/data/db
    networks:
      - task_network
    restart: always
networks:
  task_network:
    external:
      name: task_network
      